server:
  port: 8090
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: atcdi-open-gis
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
