server:
  port: 8090
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: atcdi-open-gis
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

# swagger开关
swagger:
  swagger-toggle: true

logging:
  file:
    path: src\main\resources\logger\ # logger文件夹需要提前生成
  level:
    com.atcdi: debug